# Generated by Django 4.0.1 on 2022-01-17 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notita',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 10, 4, 43, 327505, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
