# Generated by Django 4.0.1 on 2022-01-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notite', '0002_alter_notita_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notita',
            name='pub_date',
        ),
    ]
