# Generated by Django 4.0.1 on 2022-01-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notite', '0003_remove_notita_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notita',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
