# Generated by Django 4.0.1 on 2022-01-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notite', '0004_notita_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notita',
            name='pub_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
